---
title: "Home Page"
format: html
execute:
  echo: true
  warning: false
  message: false
---


```{r}
#| include: false
library(DBI)
library(RSQLite)
library(DT)

db_file <- "virtual_production.db"

# stops if no file found
stopifnot(file.exists(db_file))

con <- dbConnect(SQLite(), normalizePath(db_file, mustWork = TRUE))


```

<br> <br>

```{r}
#| echo: false
#1. List the total budget allocated for productions in each country (via Clients + Productions), 
#along with the count of projects per country. Display sorted by the total budget in
#descending order.
#defining te SQL block of data
Question_01 <- "             
SELECT
  c.Country AS Country,
  COUNT(p.ProductionID) AS ProjectCount,
  SUM(p.Budget) AS TotalBudget
FROM Clients c
JOIN Productions p ON p.ClientID = c.ClientID
GROUP BY c.Country
ORDER BY TotalBudget DESC;
"
#ceates data in memeory of the block above
Question_01_Result <- dbGetQuery(con, Question_01)         
#Presents the data in table in HTML
library(DT)
#DT::datatable(Question_01_Result, options = list(pageLength = 20), rownames = FALSE)
DT::datatable(
  Question_01_Result,
  caption = htmltools::tags$caption(
    style = "caption-side: top; font-size: 1.5em; font-weight: bold;color: black; text-align: left;",
    "Question_01: Total Budget and Project Count by Country"
  ),
  rownames = FALSE,
  options = list(pageLength = 25)
)
```
<br> <br> <br> <br>
```{r}
#| echo: false
#2. List the average development time for productions, categorized by the number of assets
#used.
#1creates a temporary table AssetsPerProduction AS  that counts how many assets are linked to each production
#2Link assets to environments, and  keep productions with no assets
#3Count the number of assets found for each production
#54count separately for each production
#6Another temp table for days of production DevelopmentTime AS
#7app.AssetCount, how many productions For each asset count
Question_02 <- "
WITH AssetsPerProduction AS (
  SELECT
    e.ProductionID,
    COUNT(a.AssetID) AS AssetCount
  FROM Environments e
  LEFT JOIN Assets a ON a.EnvironmentID = e.EnvironmentID
  GROUP BY e.ProductionID
),
DevelopmentTime AS (
  SELECT
    ProductionID,
    CAST(julianday(EndDate) - julianday(StartDate) AS INTEGER) AS DevDays
  FROM Productions
  WHERE StartDate IS NOT NULL
    AND EndDate IS NOT NULL
)
SELECT
  app.AssetCount,
  COUNT(*) AS ProductionCount,
  ROUND(AVG(dt.DevDays), 1) AS AvgDevelopmentDays
FROM AssetsPerProduction app
JOIN DevelopmentTime dt
  ON dt.ProductionID = app.ProductionID
GROUP BY app.AssetCount
ORDER BY app.AssetCount;
"
#query the db and store result in data frame
#display the results in an interactive table
Question_02_Result <- dbGetQuery(con, Question_02)
library(DT)
DT::datatable(
  Question_02_Result,
  caption = htmltools::tags$caption(
    style = "caption-side: top; font-size: 1.5em; font-weight: bold;color: black; text-align: left;",
    "Question 02: Average Development Time by Number of Assets Used"
  ),
  rownames = FALSE,
  options = list(pageLength = 25)
)

```

<br> <br> <br> <br>

```{r}
#| echo: false
#3. List the top three crew members based on the number of successful productions they’ve
#been involved in. Display the results

Question_03 <- "
SELECT
  cm.CrewID,  -- get crew ID
  cm.Name,     -- crew member name
  cm.Role,    -- their role in the crew
  COUNT(DISTINCT p.ProductionID) AS CompletedProductions  -- how many completed productions they worked in
FROM CrewMembers cm
JOIN ProductionCrew pc
  ON pc.CrewID = cm.CrewID  -- linking crew members to productions
JOIN Productions p
  ON p.ProductionID = pc.ProductionID
WHERE p.Status = 'Completed'  -- only include finished productions
GROUP BY cm.CrewID, cm.Name, cm.Role     -- group
ORDER BY CompletedProductions DESC, cm.Name ASC  -- sorts highest number first, then alphabetical 
LIMIT 3;
"

Question_03_Result <- dbGetQuery(con, Question_03)

#DT::datatable(Question_03_Result, options = list(pageLength = 8), rownames = FALSE)
DT::datatable(
  Question_03_Result,
  caption = htmltools::tags$caption(
    style = "caption-side: top; font-size: 1.5em; font-weight: bold;color: black; text-align: left;",
    "Question_03: List the top three crew members based on the number of successful productions."
  ),
  rownames = FALSE,
  options = list(pageLength = 25)
)
```
<div style="margin-top: 80px;"></div>
<h2>Part two SQL Concepts LIKE and OR</h2>

``` sql
SELECT
  ProductionID,
  Title, 
  Genre, 
  Status, 
  Budget
FROM Productions
WHERE Title LIKE '%Virtual%'
   OR Title LIKE '%Cam%'
   OR Genre LIKE '%Sci%';
```
```{r}

```
<br><br>
```{r}
#| echo: false
library(DBI)
library(DT)

Concepts_01 <- "
SELECT
  ProductionID,
  Title,
  Genre,
  Status,
  Budget
FROM Productions
WHERE Title LIKE '%Virtual%'
   OR Title LIKE '%Cam%'
   OR Genre LIKE '%Sci%';
"

resultConcept_01 <- dbGetQuery(con, Concepts_01) #run sql query using db connection, save result as a data frame

#DT::datatable(
#  result,
#  rownames = FALSE,
#  options = list(pageLength = 10, lengthChange = FALSE)
#) version below is better,displays results in an interactive table
DT::datatable(
  resultConcept_01,
  caption = htmltools::tags$caption(
    style = "caption-side: top; font-size: 1.5em; font-weight: bold;color: black; text-align: left;",
    "Part two No:1 SQL Concepts LIKE and OR output."
  ),
  rownames = FALSE,
  options = list(pageLength = 25)
)
```


<div style="margin-top: 80px;"></div>
<h2>Part two No:2 SQL DISTINCT and ORDER BY</h2>

``` sql
SELECT DISTINCT
  Country
FROM Clients
ORDER BY Country;
```
```{r}

```
<br><br>
```{r}
#| echo: false
library(DBI)
library(DT)

Concepts_02 <- "
SELECT DISTINCT
  Country
FROM Clients
ORDER BY Country;
"

concepts_02_result <- dbGetQuery(con, Concepts_02)  #run sql query using db connection, save result as a data frame

DT::datatable(
  concepts_02_result,
  caption = htmltools::tags$caption(
    style = "caption-side: top; font-size: 1.5em; font-weight: bold;color: black; text-align: left;",
    "Part two No:2 SQL DISTINCT and ORDER BY."
  ),
  rownames = FALSE,
  options = list(pageLength = 25)
)
```

<div style="margin-top: 80px;"></div>
<h2>Part two No:3 SQL Subquery with SELECT</h2>

``` sql
SELECT
  ProductionID,
  Title,
  Budget,
  Status
FROM Productions
WHERE Budget > (
  SELECT AVG(Budget)
  FROM Productions
)
ORDER BY Budget DESC;
```
```{r}

```
<br><br>
```{r}
#| echo: false
library(DBI)
library(DT)

Concepts_03 <- "
SELECT
  ProductionID,
  Title,
  Budget,
  Status
FROM Productions
WHERE Budget > (
  SELECT AVG(Budget)
  FROM Productions
)
ORDER BY Budget DESC;
"

concepts_03_result <- dbGetQuery(con, Concepts_03)  #run sql query using db connection, save result as a data frame

DT::datatable(
  concepts_03_result,
  caption = htmltools::tags$caption(
    style = "caption-side: top; font-size: 1.5em; font-weight: bold;color: black; text-align: left;",
    "Part two No:3 SQL Subquery with SELECT."
  ),
  rownames = FALSE,
  options = list(pageLength = 25)
)

```